version: '3.1'

services:
        db:
            image: redis
            ports:
                - "6379:6379"
        gibber:
            build: .
            ports:
                - "8080:8080"
            depends_on:
              - db
